[[docs]]
  name = "Veri Yapıları Giriş"
  weight = 10
  identifier = "introduction"
  url = "/docs/introduction/"

[[docs]]
  name = "Veri Yapıları I"
  weight = 20
  identifier = "veri-yapilari-1"
  url = "/docs/veri-yapilari-1/"

[[docs]]
  name = "Veri Yapıları II"
  weight = 30
  identifier = "veri-yapilari-2"
  url = "/docs/veri-yapilari-2/"

[[docs]]
  name = "Ağaç Bazlı Veri Yapıları I"
  weight = 40
  identifier = "agac-bazli-veri-yapilari-1"
  url = "/docs/agac-bazli-veri-yapilari-1/"

[[docs]]
  name = "Graf Bazlı Veri Yapıları"
  weight = 50
  identifier = "graph-bazli-veri-yapilari"
  url = "/docs/graph-bazli-veri-yapilari/"

[[docs]]
  name = "Sıralama ve Arama Algoritmaları"
  weight = 60
  identifier = "siralama-arama-algoritmalari"
  url = "/docs/siralama-arama-algoritmalari/"

[[docs]]
  name = "Aç Gözlü Algoritma"
  weight = 70
  identifier = "ac-gozlu-algoritma"
  url = "/docs/ac-gozlu-algoritma/"

[[docs]]
  name = "Dinamik Programlama"
  weight = 80
  identifier = "dinamik-programlama"
  url = "/docs/dinamik-programlama/"

[[docs]]
  name = "Diğer Algoritmalar"
  weight = 90
  identifier = "diger-algoritmalar"
  url = "/docs/diger-algoritmalar/"


[[main]]
  name = "Rehber"
  url = "/docs/introduction/what-is-the-algorithm/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/AbdullahOztuurkk/Algorithm-And-Data-Structures"
  post = "v0.1.0"
  weight = 20

# [[footer]]
#   name = "Gizlilik"
#   url = "/gizlilik-politikasi"
#   weight = 10
